### ISSUE TITLE
 How to run this project to get .tflite file ?

### ISSUE THREAD

**Issue by yash365** [sergiofraile/when_flutter_meets_tensorflow_part_1#1]

**Comment by sergiofraile** [comment]
@yash365 everything is described in the article
https://medium.com/flutter-community/handwriting-number-recognizer-with-flutter-and-tensorflow-part-i-414157b7574f

You can either open the .ipynb in a jupiter notebook (any will open it, but I recommend using colab https://colab.research.google.com/) or running the python script on your own machine
